version: "3.8"
services:
  worker:
    container_name: worker
    build: .
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        if [ ! -f /data/keys/priv.bin ]; then
          echo "Generating new private keys..."
          mkdir -p /data/keys
          cd /data/keys
          allora-keys
        fi
        # Change boot-nodes below to the key advertised by your head
        allora-node --role=worker --peer-db=/data/peerdb --function-db=/data/function-db \
          --runtime-path=/app/runtime --runtime-cli=bls-runtime --workspace=/data/workspace \
          --private-key=/data/keys/priv.bin --log-level=debug --port=9011 \
          --boot-nodes=/ip4/172.19.0.100/tcp/9010/p2p/head-id \
          --topic=2
    volumes:
      - type: bind
        source: ./worker-data
        target: /data
    env_file:
      - .env
    depends_on:
      - head
    networks:
      b7s-local:
        aliases:
          - worker
        ipv4_address: 172.19.0.5

  head:
    container_name: head
    image: alloranetwork/allora-inference-base-head:v0.0.5
    environment:
      - HOME=/data
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        if [ ! -f /data/keys/priv.bin ]; then
          echo "Generating new private keys..."
          mkdir -p /data/keys
          cd /data/keys
          allora-keys
        fi
        allora-node --role=head --peer-db=/data/peerdb --function-db=/data/function-db  \
          --runtime-path=/app/runtime --runtime-cli=bls-runtime --workspace=/data/workspace \
          --private-key=/data/keys/priv.bin --log-level=debug --port=9010 --rest-api=:6000
    ports:
      - "6000:6000"
    volumes:
      - ./head-data:/data

    networks:
      b7s-local:
        aliases:
          - head
        ipv4_address: 172.19.0.100

networks:
  b7s-local:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24

volumes:
  worker-data:
  head-data:
